### ISSUE TITLE
Add 2dsphere index to schema

### ISSUE THREAD

**Issue by lpirola** [RideAmigosCorp/mongoose-geojson-schema#5]
i suggest that would be nice if we could add index to schema.

What you guys think?

**Comment by lorlab** [comment]
Hi. I'll write here instead of opening a new issue because my problem has to do with a 2dshpere index.

I am trying to add an index to my schema:

    var userSchema = mongoose.Schema({
        email: { type: String, unique: true },
        loc: { type: GeoJSON.Point, index: '2dsphere' }
    });

but I get this error:

    TypeError: Undefined type at `loc.index`
    Did you try nesting Schemas? You can only nest using refs or arrays.

I apologize if this is my fault, as I am new to mongoose, however I tried using a simple [Number] (which is the old way of storing coordinates, and I see lots of examples of this around) instead of GeoJSON.Point and it worked. Any suggestions? Thanks!

**Comment by voronianski** [comment]
@lpirola @markstos do you have some recipe how to add `2dsphere` index, currently I'm trying:

```javascript
new Schema({
    district: {
        type: String,
        trim: true,
        unique: true,
        required: true
    },
    area: {
        type: GeoJSON.FeatureCollection,
        index: '2dsphere'
    }
});
```

but getting such error:

```bash
/Users/dmitri/api/node_modules/mongoose/lib/schema.js:479
    throw new TypeError('Undefined type `' + name + '` at `' + path +
          ^
TypeError: Undefined type `2dsphere` at `area.index`
  Did you try nesting Schemas? You can only nest using refs or arrays.
```

**Comment by lpirola** [comment]
@voronianski i don't use 2dsphere. Here my example on working with geojson schema. https://github.com/nucleo-digital/gestaourbana-mapas/blob/master/app/layers/LayerModel.js

**Comment by markstos** [comment]
The recommended practice is define your index separately, using the `index` method.  See:

http://mongoosejs.com/docs/api.html#schema_Schema-index

If this seems helpful to document in the README, a doc-patch is welcome. 

Closing.
